import {
  Sparkles, Cpu, Bot, Languages, Eye, Brain, MessageSquare, Layers, Thermometer, Hash,
  BookOpen, AlertTriangle, Gauge, Unlock, Wrench, Wand2, FileCode2, Zap, ListOrdered,
  StepForward, Repeat, Link2, RefreshCw, Settings, Puzzle, Database, FolderSearch,
  Boxes, Table, Compass, Users, Plug, KeyRound, Network, Server, MonitorPlay,
  Rocket, HardDrive, Cloud, Router, Minimize2, GraduationCap, Tag, Shuffle, Trophy,
  Handshake, Circle, Sigma, Scale, Ruler, Activity, TrendingUp, TrendingDown, SlidersHorizontal,
  Box, Timer, AlertOctagon, Blocks, Grid3x3, Image as ImageIcon, Clock, Infinity as InfinityIcon,
  ArrowDownUp, ArrowUpDown, Archive, Filter, Shrink, Sparkle, Focus, Split, Layers3,
  Palette, MessageCircle, FlaskConical, Github, Store, LinkIcon, GraduationCap as GradCap2,
  ShieldAlert, Shield, EyeOff, EyeClosed, UserX, Bug, MailWarning, VideoOff, Crosshair, LineChart,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type GlossaryTerm = { term: string; definition: string; icon: LucideIcon };
export type GlossarySection = { title: string; terms: GlossaryTerm[] };

export const glossary: GlossarySection[] = [
  {
    title: "General AI",
    terms: [
      { term: "Algorithm", icon: ListOrdered, definition: "A set of instructions that a computer follows to perform a specific task." },
      { term: "Artificial Intelligence (AI)", icon: Sparkles, definition: "The overarching term for algorithms that can exhibit intelligent behavior, like learning, reasoning, and problem-solving." },
      { term: "Artificial General Intelligence (AGI)", icon: Brain, definition: "A theoretical, advanced form of AI designed to understand, learn, and apply knowledge across any intellectual task at a level equal to or exceeding human capabilities." },
      { term: "Natural Language (NL)", icon: Languages, definition: "The language humans use to communicate with each other, including spoken and written forms." },
      { term: "Natural Language Processing (NLP)", icon: MessageSquare, definition: "A field of AI that focuses on algorithms being able to interpret, manipulate, and comprehend human language." },
      { term: "Computer Vision", icon: Eye, definition: "A field of AI concerned with algorithms that understand and process visual information from the real world." },
      { term: "Large Language Model (LLM)", icon: BookOpen, definition: "A powerful AI model trained on massive amounts of text data. LLMs can generate text, translate languages, write different kinds of creative content, and answer your questions in an informative way." },
      { term: "Chatbots", icon: Bot, definition: "A computer program that simulates a conversation between human users and a Large Language Model." },
      { term: "Multimodal", icon: Layers, definition: "A description of a model that allows users to integrate multiple input layers — text, images, and video — to generate more comprehensive and contextually rich outputs." },
      { term: "Temperature", icon: Thermometer, definition: "A parameter that controls the randomness of generated text. Higher = more creative and surprising; lower = more conservative and predictable." },
      { term: "Tokens", icon: Hash, definition: "The numerical representation of the input data an AI model processes. Text is broken into words/subwords and given number IDs; tokens also represent images, video, and audio." },
      { term: "Context Window", icon: Focus, definition: "The amount of information an AI model can consider when generating a response, measured by token count." },
      { term: "Hallucination", icon: AlertTriangle, definition: "When an AI generates inaccurate, biased, or otherwise unintended information as a response." },
      { term: "Benchmark Evaluation", icon: Gauge, definition: "Standardized tests, datasets, and metrics used to objectively measure and compare the performance, accuracy, and capabilities of AI models." },
      { term: "Open Source", icon: Unlock, definition: "Software or data freely available to use, modify, and distribute. Most local AI models are 'open weight' rather than fully open source." },
      { term: "Fine-tuning", icon: Wrench, definition: "Taking a pre-trained model and further training it on a smaller, task-specific dataset to improve performance on that task." },
    ],
  },
  {
    title: "Prompt Engineering",
    terms: [
      { term: "Prompt Engineering", icon: Wand2, definition: "The art of crafting instructions and context for an AI model to get the desired response." },
      { term: "Prompt Template", icon: FileCode2, definition: "A pre-defined structure or format for guiding an LLM's response — placeholders for user input, instructions, and output formatting." },
      { term: "Zero Shot Prompting", icon: Zap, definition: "The LLM performs a task without any task-specific examples, relying entirely on its pre-trained knowledge." },
      { term: "Few Shot Prompting", icon: Puzzle, definition: "The prompt supplies example input/response pairs so the model learns the task and output format." },
      { term: "Chain of Thought Prompting", icon: StepForward, definition: "Breaks a complex task into a series of reasoning steps within one prompt so the AI works through the problem." },
      { term: "Least to Most Prompting", icon: TrendingUp, definition: "Start with a basic prompt and gradually add detail or instructions until the model produces the desired response." },
      { term: "Prompt Chaining", icon: Link2, definition: "Breaks a prompt into multiple subtasks, useful for long generations or complex, multi-step work." },
      { term: "Iterative Prompting", icon: RefreshCw, definition: "Refine the prompt in stages based on the model's responses — a back-and-forth conversation to steer output." },
      { term: "System Prompt", icon: Settings, definition: "A behind-the-scenes meta-prompt that defines an AI model's persona, behavior, rules, and constraints before user interaction." },
    ],
  },
  {
    title: "Tool Calling / Agents",
    terms: [
      { term: "Function / Tool Calling", icon: Wrench, definition: "The model's ability to trigger pre-defined functions or tools that fetch external data or perform tasks to enrich responses." },
      { term: "Retrieval Augmented Generation (RAG)", icon: FolderSearch, definition: "Connecting an LLM to an external data source (often private or unstructured) via a vector database to ground answers in that data." },
      { term: "Indexing", icon: Table, definition: "Formatting a database so specific data can be retrieved via a query — structured or natural language." },
      { term: "Embeddings", icon: Boxes, definition: "A vector of floating-point numbers representing data points. They capture semantic meaning for fast similarity search." },
      { term: "Vector Database", icon: Database, definition: "A database optimized to store and search vector embeddings by similarity, letting you find items with related meaning." },
      { term: "K Nearest Neighbor Search (KNN)", icon: Compass, definition: "A machine-learning algorithm that finds the k closest data points to a query using a distance metric (e.g., cosine similarity)." },
      { term: "Agents", icon: Users, definition: "An AI model that chooses its own sequence of actions to complete versatile tasks, rather than following a hardcoded path." },
      { term: "Application Programming Interface (API)", icon: Plug, definition: "A bridge between software applications — defined functions that let programs communicate and exchange data." },
      { term: "API Key", icon: KeyRound, definition: "A unique identifier used to authenticate access to an API, acting like a password that unlocks its features." },
      { term: "Model Context Protocol (MCP)", icon: Network, definition: "An open standard that enables secure, two-way connections between data sources and AI agents." },
    ],
  },
  {
    title: "Computational Processing",
    terms: [
      { term: "Central Processing Unit (CPU)", icon: Cpu, definition: "The 'brain' of a computer — a small number of powerful cores optimized for a wide range of sequential tasks." },
      { term: "Graphics Processing Unit (GPU)", icon: MonitorPlay, definition: "A specialized processor with many cores for parallel processing — great for graphics and deep-learning training." },
      { term: "Tensor Processing Unit (TPU)", icon: Sigma, definition: "A Google-designed hardware accelerator optimized for tensor operations, offering high throughput and energy efficiency for ML workloads." },
      { term: "Quantum Processing Unit (QPU)", icon: Sparkle, definition: "Cutting-edge computing that uses quantum mechanics to perform certain computations exponentially faster than classical hardware." },
      { term: "Local Model", icon: HardDrive, definition: "A machine-learning model trained and run entirely on a user's device — private, offline-capable, but limited by device resources." },
      { term: "Compute Unified Device Architecture (CUDA)", icon: Server, definition: "NVIDIA's parallel computing platform and programming model that lets developers offload workloads to GPUs." },
      { term: "Cloud Computing Platforms", icon: Cloud, definition: "On-demand computing resources — servers, storage, databases, and tools — delivered over the internet (AWS, Azure, GCP)." },
      { term: "Edge Devices", icon: Router, definition: "Computing devices at the edge of a network, closer to where data is generated — reduce latency for real-time AI." },
      { term: "Quantization", icon: Minimize2, definition: "Reducing the numerical precision of model weights (e.g. 32-bit → 8-bit) to shrink size, speed up inference, and lower memory usage." },
    ],
  },
  {
    title: "Machine Learning",
    terms: [
      { term: "Training", icon: GraduationCap, definition: "Teaching an AI model by feeding it data, analyzing results, and adjusting outputs to improve accuracy and efficiency." },
      { term: "Supervised Learning", icon: Tag, definition: "Training that relies on labeled input/output pairs used to compute cost and adjust weights and biases." },
      { term: "Unsupervised Learning", icon: Shuffle, definition: "Training on unlabeled data to uncover hidden patterns or structures within the data itself." },
      { term: "Reinforcement Learning (RL)", icon: Trophy, definition: "An agent learns by trial and error in an environment, receiving rewards or penalties and maximizing long-term reward." },
      { term: "Reinforcement Learning from Human Feedback (RLHF)", icon: Handshake, definition: "Reinforcement learning guided by human feedback on the agent's actions rather than solely pre-defined rewards." },
      { term: "Neuron", icon: Circle, definition: "A processing unit of a neural network. It receives input, performs a calculation, and outputs a single value." },
      { term: "Weight", icon: Scale, definition: "A numerical value on the connection between two neurons. It sets the strength of the signal passed along." },
      { term: "Bias (Neural Network Element)", icon: SlidersHorizontal, definition: "A constant added to a neuron's weighted input, letting it shift its activation output independent of the inputs." },
      { term: "Parameter Size", icon: Box, definition: "The total count of adjustable variables inside an AI model that are learned during training." },
      { term: "Forward Pass", icon: ArrowUpDown, definition: "Calculating and storing intermediate values from input layer to output layer during a neural network's prediction." },
      { term: "Cost / Loss Function", icon: Ruler, definition: "A function that quantifies how wrong a network's prediction is. Loss = single sample; cost = average across samples." },
      { term: "Metric", icon: Activity, definition: "A quantitative measure — accuracy, precision, recall, F1, MSE, R² — used to evaluate model performance." },
      { term: "Backpropagation", icon: ArrowDownUp, definition: "Adjusting a network's weights and biases backward from the cost, teaching the model to improve future predictions." },
      { term: "Gradient Descent", icon: TrendingDown, definition: "An optimization algorithm that iteratively nudges weights and biases in the direction that lowers the cost function." },
      { term: "Hyperparameter", icon: SlidersHorizontal, definition: "Settings that control the learning process (not learned from data) — set by the developer before training." },
      { term: "Batch Size", icon: Blocks, definition: "The number of training examples processed together in one forward pass. Impacts training speed and stability." },
      { term: "Epoch", icon: Timer, definition: "One complete pass through the entire training dataset. Models typically run for many epochs." },
      { term: "Overfitting", icon: AlertOctagon, definition: "When a model memorizes the training data too well and fails to generalize to unseen examples." },
    ],
  },
  {
    title: "Models",
    terms: [
      { term: "Model Architecture", icon: Grid3x3, definition: "The structure and design of an ML model — network type, layer/neuron counts, activation functions, etc." },
      { term: "Feed Forward Neural Network (FNN)", icon: ArrowUpDown, definition: "The simplest neural network — stacked fully connected layers where information flows only forward, input to output." },
      { term: "Convolutional Neural Network (CNN)", icon: ImageIcon, definition: "A neural network built for images. Filters (kernels) slide across the input to extract features like edges and shapes." },
      { term: "Recurrent Neural Network (RNN)", icon: Repeat, definition: "A neural network for sequential data. Loops let information persist so the model can 'remember' what it processed before." },
      { term: "Long Short-Term Memory (LSTM)", icon: Clock, definition: "A specialized RNN with memory cells and gates that can learn long-range dependencies in sequential data." },
      { term: "Exploding Gradient Problem", icon: TrendingUp, definition: "During training with long sequences, recurrent weights above 1 grow exponentially, making learning unstable." },
      { term: "Vanishing Gradient Problem", icon: TrendingDown, definition: "During training with long sequences, recurrent weights below 1 shrink toward zero, so early inputs stop influencing learning." },
      { term: "Encoder", icon: Shrink, definition: "Compresses input (image, text, sequence) into a smaller latent representation that captures its essential features." },
      { term: "Decoder", icon: Split, definition: "Expands a latent code back into the original data or something similar to it." },
      { term: "Autoencoder", icon: Layers3, definition: "An encoder + decoder trained to reconstruct the input from a compressed representation (the bottleneck)." },
      { term: "Denoising Autoencoder (DAE)", icon: Filter, definition: "An autoencoder trained to remove noise, reconstructing a clean signal from a corrupted input." },
      { term: "Variational Autoencoder (VAE)", icon: Archive, definition: "An autoencoder that learns a probabilistic latent space — useful for dimensionality reduction and generating new samples." },
      { term: "Transformer", icon: InfinityIcon, definition: "A model architecture built on attention that revolutionized NLP by capturing context and relationships across a sequence." },
      { term: "Attention", icon: Crosshair, definition: "A mechanism that lets a network focus on the most relevant parts of the input when processing sequences." },
      { term: "Self-Attention", icon: Focus, definition: "Attention applied within a single sequence — the model attends to different parts of its own input for context." },
      { term: "Multi-Head Attention", icon: LineChart, definition: "Runs multiple self-attention patterns in parallel so the model can capture diverse relationships at once." },
      { term: "Diffusion Model", icon: Palette, definition: "Generates realistic media by learning to reverse a noise-adding process — used in DALL·E and Stable Diffusion." },
    ],
  },
  {
    title: "Platforms",
    terms: [
      { term: "ChatGPT", icon: MessageCircle, definition: "OpenAI's chatbot application powered by their large language models." },
      { term: "Google AI Studio", icon: FlaskConical, definition: "A web app powered by Google's Gemini models with advanced access to system prompts, temperature, and other parameters." },
      { term: "n8n", icon: Network, definition: "A node-based workflow automation tool that connects web apps, databases, and AI models." },
      { term: "Ollama", icon: HardDrive, definition: "An open-source tool that makes it easy to run and manage large language models directly on your own computer." },
      { term: "Open WebUI", icon: MonitorPlay, definition: "A self-hosted, ChatGPT-style interface for interacting with local and remote large language models." },
      { term: "GitHub", icon: Github, definition: "The world's largest source-code host — a web platform built on Git for storing, managing, and collaborating on code." },
      { term: "Hugging Face", icon: Store, definition: "The 'GitHub for AI' — repositories of open-source models, datasets, and tools for many AI tasks." },
      { term: "LangChain", icon: LinkIcon, definition: "An open-source library for building AI assistants — tools for prompts, model integration, and app orchestration." },
      { term: "Teachable Machine", icon: GradCap2, definition: "A free Google tool that lets anyone train image, sound, and pose classifiers in the browser without writing code." },
    ],
  },
  {
    title: "Ethics and Safety",
    terms: [
      { term: "AI Ethics", icon: Shield, definition: "A branch of ethics focused on the responsible development, deployment, and use of AI — fairness, transparency, privacy, and safety." },
      { term: "Bias (Ethical)", icon: Scale, definition: "A disproportionate weight for or against an idea or group — often inaccurate, closed-minded, prejudicial, or unfair." },
      { term: "Explicit Bias", icon: Eye, definition: "Conscious attitudes or prejudices that a person is aware of and can articulate — deliberate and intentional." },
      { term: "Implicit Bias", icon: EyeOff, definition: "Unconscious attitudes or stereotypes that influence judgments and behavior without a person's awareness." },
      { term: "Selection Bias", icon: Filter, definition: "When training data doesn't represent the reality being modeled — often from incomplete data or biased sampling." },
      { term: "Confirmation Bias", icon: EyeClosed, definition: "When an AI over-relies on pre-existing beliefs or trends in the data, reinforcing them and missing new patterns." },
      { term: "Stereotyping Bias", icon: UserX, definition: "Generalizing about entire groups, leading to inaccurate predictions for individuals — perpetuated by biased training data." },
      { term: "Measurement Bias", icon: Ruler, definition: "Bias introduced by how data is measured or interpreted — flawed metrics can produce biased conclusions." },
      { term: "Shadow AI", icon: EyeOff, definition: "Unauthorized AI use inside an organization — risks include data breaches, algorithmic bias, and compliance failures." },
      { term: "Adversarial Attacks", icon: Bug, definition: "Malicious manipulation techniques that trick AI algorithms into making incorrect or harmful decisions." },
      { term: "Malware", icon: Bug, definition: "Malicious software — viruses, worms, ransomware, spyware — designed to harm systems or steal data." },
      { term: "Misinformation", icon: MailWarning, definition: "False or inaccurate information that spreads regardless of intent to deceive, potentially influencing decisions." },
      { term: "Deepfake", icon: VideoOff, definition: "Synthetic media that uses deep learning to create realistic but manipulated videos or audio recordings." },
      { term: "Lethal Autonomous Weapons System (LAWS)", icon: ShieldAlert, definition: "AI-driven weapons capable of making life-and-death decisions without human intervention — a significant ethical concern." },
      { term: "Algorithmic Trading Manipulation", icon: TrendingUp, definition: "Exploiting AI trading algorithms to manipulate markets, run pump-and-dump schemes, or commit financial fraud." },
    ],
  },
];
