/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWhiteboardsIndexRouteImport } from './routes/_authenticated/whiteboards.index'
import { Route as AuthenticatedModulesIndexRouteImport } from './routes/_authenticated/modules.index'
import { Route as ApiPublicVerifyGithubRouteImport } from './routes/api/public/verify-github'
import { Route as AuthenticatedWhiteboardsIdRouteImport } from './routes/_authenticated/whiteboards.$id'
import { Route as AuthenticatedModulesSlugRouteImport } from './routes/_authenticated/modules.$slug'
import { Route as AuthenticatedAssignmentsIdRouteImport } from './routes/_authenticated/assignments.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhiteboardsIndexRoute =
  AuthenticatedWhiteboardsIndexRouteImport.update({
    id: '/whiteboards/',
    path: '/whiteboards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesIndexRoute =
  AuthenticatedModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicVerifyGithubRoute = ApiPublicVerifyGithubRouteImport.update({
  id: '/api/public/verify-github',
  path: '/api/public/verify-github',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhiteboardsIdRoute =
  AuthenticatedWhiteboardsIdRouteImport.update({
    id: '/whiteboards/$id',
    path: '/whiteboards/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesSlugRoute =
  AuthenticatedModulesSlugRouteImport.update({
    id: '/modules/$slug',
    path: '/modules/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsIdRoute =
  AuthenticatedAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/modules/$slug': typeof AuthenticatedModulesSlugRoute
  '/whiteboards/$id': typeof AuthenticatedWhiteboardsIdRoute
  '/api/public/verify-github': typeof ApiPublicVerifyGithubRoute
  '/modules/': typeof AuthenticatedModulesIndexRoute
  '/whiteboards/': typeof AuthenticatedWhiteboardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/modules/$slug': typeof AuthenticatedModulesSlugRoute
  '/whiteboards/$id': typeof AuthenticatedWhiteboardsIdRoute
  '/api/public/verify-github': typeof ApiPublicVerifyGithubRoute
  '/modules': typeof AuthenticatedModulesIndexRoute
  '/whiteboards': typeof AuthenticatedWhiteboardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/_authenticated/modules/$slug': typeof AuthenticatedModulesSlugRoute
  '/_authenticated/whiteboards/$id': typeof AuthenticatedWhiteboardsIdRoute
  '/api/public/verify-github': typeof ApiPublicVerifyGithubRoute
  '/_authenticated/modules/': typeof AuthenticatedModulesIndexRoute
  '/_authenticated/whiteboards/': typeof AuthenticatedWhiteboardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unauthorized'
    | '/admin'
    | '/classes'
    | '/dashboard'
    | '/portfolio'
    | '/profile'
    | '/u/$username'
    | '/assignments/$id'
    | '/modules/$slug'
    | '/whiteboards/$id'
    | '/api/public/verify-github'
    | '/modules/'
    | '/whiteboards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unauthorized'
    | '/admin'
    | '/classes'
    | '/dashboard'
    | '/portfolio'
    | '/profile'
    | '/u/$username'
    | '/assignments/$id'
    | '/modules/$slug'
    | '/whiteboards/$id'
    | '/api/public/verify-github'
    | '/modules'
    | '/whiteboards'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/u/$username'
    | '/_authenticated/assignments/$id'
    | '/_authenticated/modules/$slug'
    | '/_authenticated/whiteboards/$id'
    | '/api/public/verify-github'
    | '/_authenticated/modules/'
    | '/_authenticated/whiteboards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicVerifyGithubRoute: typeof ApiPublicVerifyGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whiteboards/': {
      id: '/_authenticated/whiteboards/'
      path: '/whiteboards'
      fullPath: '/whiteboards/'
      preLoaderRoute: typeof AuthenticatedWhiteboardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/': {
      id: '/_authenticated/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof AuthenticatedModulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/verify-github': {
      id: '/api/public/verify-github'
      path: '/api/public/verify-github'
      fullPath: '/api/public/verify-github'
      preLoaderRoute: typeof ApiPublicVerifyGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whiteboards/$id': {
      id: '/_authenticated/whiteboards/$id'
      path: '/whiteboards/$id'
      fullPath: '/whiteboards/$id'
      preLoaderRoute: typeof AuthenticatedWhiteboardsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/$slug': {
      id: '/_authenticated/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof AuthenticatedModulesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/$id': {
      id: '/_authenticated/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AuthenticatedAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAssignmentsIdRoute: typeof AuthenticatedAssignmentsIdRoute
  AuthenticatedModulesSlugRoute: typeof AuthenticatedModulesSlugRoute
  AuthenticatedWhiteboardsIdRoute: typeof AuthenticatedWhiteboardsIdRoute
  AuthenticatedModulesIndexRoute: typeof AuthenticatedModulesIndexRoute
  AuthenticatedWhiteboardsIndexRoute: typeof AuthenticatedWhiteboardsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAssignmentsIdRoute: AuthenticatedAssignmentsIdRoute,
  AuthenticatedModulesSlugRoute: AuthenticatedModulesSlugRoute,
  AuthenticatedWhiteboardsIdRoute: AuthenticatedWhiteboardsIdRoute,
  AuthenticatedModulesIndexRoute: AuthenticatedModulesIndexRoute,
  AuthenticatedWhiteboardsIndexRoute: AuthenticatedWhiteboardsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicVerifyGithubRoute: ApiPublicVerifyGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
