DO $mig$
DECLARE
  readme_primer text := $md$<!-- primer:readme -->
### Concept primer: What is a README and why does it matter?

A **README** is the first file anyone sees when they open a project on GitHub. GitHub automatically shows it on the repository's front page, so it acts like the cover, back-cover blurb, and instruction manual of your project all at once. Colleges, employers, and other students judge a project in seconds — the README is what tells them what they are looking at, what you built, and why it matters, before they ever look at your files.

**What "README.md" means.** The name is a convention from the earliest days of software: files literally labeled "READ ME" so people would open them first. The `.md` extension means the file is written in **Markdown** — a plain-text way of writing that turns simple symbols into formatting when displayed:

- `#`, `##`, `###` at the start of a line become headings (biggest to smallest).
- `**bold**` becomes **bold**, `*italic*` becomes *italic*.
- A dash `-` at the start of a line becomes a bullet point.
- Triple backticks fence a block of code so it displays in a monospace box.
- `[label](https://url)` becomes a clickable link, and `![alt](image.png)` embeds an image.

Markdown exists because writing HTML is noisy for humans and plain text is hard to scan. Markdown reads clearly as text *and* renders beautifully on GitHub — one file works everywhere.

**Why READMEs follow a predictable format.** A reviewer skims dozens of projects. A predictable structure means they can find the answer to their question in one glance. The standard sections and the questions they answer:

1. **Title (H1)** — What is this project called?
2. **Short description** — In one or two sentences, what does it do and who is it for?
3. **AI tool used** — Which AI you used (ChatGPT, Claude, Firefly, etc.). This is required in this course because it is honest, and because reviewers want to see how you worked with AI.
4. **Skills practiced** — The concrete skills a college or employer can credit you for.
5. **How I made it** — Your process: what you asked the AI, how you revised the output, how you finished. This shows you *directed* the AI instead of copying its first answer.
6. **Screenshots / files** — Proof it exists. Images embed with `![description](filename.png)`.
7. **Reflection** — What you learned. This is the part that turns a project into a *portfolio* project.

**How to publish to GitHub (the mechanics).**

1. Sign in at [github.com](https://github.com) with your student account.
2. Click **New repository** (green button, top left).
3. Give it a clear name (example: `ai-portfolio-<project-name>`). Keep it **Public**. Check **Add a README**. Click **Create repository**.
4. On the repo page, click **Add file → Upload files**. Drag every project file (images, PDFs, screenshots, exported files) into the box.
5. Type a commit message like `Add project files` and click **Commit changes**. A **commit** is just a saved snapshot with a note attached — it's how GitHub tracks *what* changed and *why*.
6. Click **README.md**, then the pencil icon to edit. Paste the README template from this assignment and fill it in. Commit.
7. Copy the repository URL from your browser's address bar, paste it into the submission box, and click **Verify**.

**Common beginner mistakes to avoid.**

- Leaving placeholder text like "Coming soon" in the final README.
- Not embedding screenshots (the reviewer has to guess what your project looks like).
- Skipping the AI tool section — this course requires it and reviewers look for it first.
- Making the repo **Private** by accident. If reviewers cannot open the URL, it cannot be graded.

---
$md$;

  platform_primers jsonb := $json$
{
  "GitHub": "<!-- primer:platform:github -->\n### Concept primer: What is GitHub and why does every AI project live there?\n\n**GitHub** is the world's largest place where people store, share, and collaborate on projects — originally code, but today anything made of files: writing, designs, presentations, images, research. Think of it as a mix of Google Drive, LinkedIn, and a portfolio site, built specifically around projects.\n\n**Why we use it in this course.** A GitHub profile is portable proof of your work. Unlike a Google Doc that only your teacher sees, a public GitHub repository has a permanent URL you can put on a college application, a résumé, or a scholarship form — and the reviewer can open it instantly, no login required. Your **profile page** at `github.com/<username>` becomes a live portfolio that updates every time you publish a new project.\n\n**Key words you'll see over and over.**\n\n- **Repository (or \"repo\")** — one project folder. Each assignment in this course lives in its own repo.\n- **README** — the front-page document GitHub shows when someone opens a repo (see the README primer below).\n- **Commit** — a saved snapshot of your files with a note describing what changed. Every edit you make on GitHub is a commit.\n- **Public vs. Private** — public repos are visible to anyone with the URL. In this course you'll use **Public** so reviewers can grade them.\n- **Profile README** — a special repo whose name matches your username exactly; its README shows up at the top of your profile page.\n\n**Why the profile matters even before you have projects.** The profile is the landing page. A clean bio, a real photo, a short \"what I'm learning\" section, and a placeholder list of upcoming projects already tells a reviewer: this person takes their work seriously and knows how to present it.\n\n---\n",

  "ChatGPT": "<!-- primer:platform:chatgpt -->\n### Concept primer: What is ChatGPT and what is it good at?\n\n**ChatGPT** is a conversational AI made by OpenAI. You type a question or instruction (a **prompt**), and it writes back in natural language. Under the hood it's a *large language model* — a program trained on huge amounts of text that learned to predict which words come next in a sensible way. It doesn't \"know\" things the way a person does; it produces very fluent, statistically likely writing. That's why it can sound confident and still be wrong — a mistake called a **hallucination**.\n\n**What it's genuinely good at.**\n\n- Explaining a topic at whatever level you ask for (\"explain like I'm in 9th grade\").\n- Turning messy notes into structured writing (outlines, study guides, summaries).\n- Brainstorming lots of options quickly (titles, ideas, angles).\n- Rewriting your own draft in a different tone or shortening it.\n\n**What it's bad at — and how you protect yourself.**\n\n- Facts, dates, statistics, and citations. Always verify important claims against a second source.\n- Anything happening right now. The model has a knowledge cutoff.\n- Personal, private, or confidential information. Don't paste anything you wouldn't want stored on someone else's server.\n\n**Prompting basics.** A useful prompt tells ChatGPT three things: **who it is** (\"You are a college admissions coach…\"), **what you want** (\"Write a 250-word study guide on the causes of WWI…\"), and **how it should look** (\"…in bullet points, with a short quiz at the end.\"). If the first answer is off, don't start over — reply with a correction (\"Shorter. No dates before 1900. Add a summary sentence.\"). Iterating is the skill.\n\n---\n",

  "Claude": "<!-- primer:platform:claude -->\n### Concept primer: What is Claude and when should you reach for it?\n\n**Claude** is a conversational AI made by Anthropic. Like ChatGPT, it's a large language model — you give it a prompt, it responds in natural language. Claude was designed with an emphasis on *safety, thoughtful reasoning, and long documents*, which is why this course uses it for the reading, writing-partner, and long-form assignments.\n\n**What makes Claude a good fit for these projects.**\n\n- **Long context window** — you can paste a full article, chapter, or transcript and ask Claude to work with all of it at once, instead of chopping it into pieces.\n- **Careful, structured reasoning** — Claude tends to explain its thinking and cite specific passages when you ask it to. Perfect for deep-reading companions, source analysis, and editing partners.\n- **Willingness to push back** — Claude will more readily say \"here is a counter-argument\" or \"this claim is thin,\" which is exactly what you want from an editor or debate partner.\n\n**Same warnings as any AI.** Claude can still be confidently wrong. If it quotes a source, verify the quote actually appears in the document. If it summarizes a chapter, spot-check the summary against the real text before you use it.\n\n**Prompting tip specific to Claude.** Claude responds especially well to *role + task + format + constraints* prompts: \"Act as my editor. Read the op-ed I paste below. Give me three specific suggestions to strengthen the argument. Quote the exact sentence you'd change. Do not rewrite the whole piece.\"\n\n---\n",

  "Canva AI": "<!-- primer:platform:canva -->\n### Concept primer: What is Canva and what do the AI features actually do?\n\n**Canva** is a drag-and-drop design app used by millions of students, small businesses, and nonprofits to make posters, social posts, presentations, logos, infographics, and more. Its power for beginners is that it starts you with professionally designed templates — you don't have to be a designer to end up with something that looks like one made it.\n\n**Canva's AI tools (\"Magic Studio\") in plain language.**\n\n- **Magic Design** — you type what you want (\"a poster for a school recycling drive\") and Canva generates a full design you can then edit.\n- **Magic Write** — writes or rewrites the words *inside* your design (headlines, body copy, captions).\n- **Text to Image** — generates an image from a description, so you don't need to hunt for stock photos.\n- **Magic Edit / Magic Eraser** — remove or replace parts of an existing photo (a background, an object).\n- **Brand Kit** — saves your colors, fonts, and logo so every design you make stays consistent.\n\n**Why design skills matter in a portfolio.** A great idea explained in an ugly document loses to an average idea explained in a clear, well-designed one — over and over. Reviewers, teachers, and future employers read visuals *before* they read words. Design isn't decoration; it's how your message gets a fair hearing.\n\n**Beginner rules that make anything look better.**\n\n- Pick **two fonts maximum** — one for headings, one for body.\n- Pick **three colors maximum** — one main, one accent, one neutral.\n- **Align everything** — left edges of text should line up, not float randomly.\n- **Leave whitespace** — cramped is amateur; breathing room is professional.\n\n---\n",

  "NotebookLM": "<!-- primer:platform:notebooklm -->\n### Concept primer: What is NotebookLM and why is it different?\n\n**NotebookLM** is a research and study tool from Google. What makes it different from ChatGPT or Claude is a single, powerful rule: it only answers using the **sources you upload**. You feed it PDFs, Google Docs, web links, YouTube videos, or pasted text — and it becomes an AI assistant that has read *only your materials*. It won't invent facts from elsewhere, and every answer links back to the exact passage it came from.\n\n**Why that matters for school and portfolios.**\n\n- **Fewer hallucinations.** If a fact isn't in your sources, NotebookLM says so instead of making one up. That makes it far safer for research.\n- **Grounded citations.** Every claim in an answer is a clickable citation back to the original document. Perfect for essays, literature reviews, and study guides.\n- **Audio Overviews (\"podcasts\").** NotebookLM can generate a natural-sounding two-host podcast episode that explains your uploaded sources in conversation. It's a great way to turn class notes or research into a study aid you can listen to.\n\n**How a NotebookLM \"notebook\" is organized.** A **notebook** is a project. You add **sources** (up to dozens of files), then chat with them, generate summaries, timelines, FAQs, study guides, briefing docs, or the audio overview. You can share a notebook with a link so classmates or reviewers can explore the same sources.\n\n**Same warning as always.** \"Grounded in your sources\" only means the AI is quoting *your uploads*. If your sources are wrong or biased, the answers will be wrong or biased too. Choose sources carefully.\n\n---\n",

  "NapkinAI": "<!-- primer:platform:napkin -->\n### Concept primer: What is Napkin AI and what problem does it solve?\n\n**Napkin AI** turns your text into diagrams. You paste an idea, a paragraph, a process, or an outline, and Napkin generates visual options — flowcharts, timelines, concept maps, org charts, comparison tables — that you can pick from and edit. The name comes from the classic idea of sketching a plan on the back of a napkin. Napkin does that step for you, well and fast.\n\n**Why visuals matter.** A wall of text buries the point. A diagram makes structure visible in a single glance: *this leads to that, these three things are parallel, this is a cycle, this is a comparison.* When a reviewer sees a diagram in your project, they immediately trust that you actually understood the topic — because you couldn't have built the diagram otherwise.\n\n**When to use it in this course.**\n\n- To turn a research summary into a concept diagram.\n- To document a real workflow you follow (studying, morning routine, a club's process).\n- To build a slide of visuals for a pitch or storytelling deck instead of another bullet list.\n\n**How to get good results.**\n\n- Give Napkin *structured* text — steps as a numbered list, comparisons as a table — and it will produce cleaner diagrams than if you paste a wall of prose.\n- Generate several options. Napkin usually offers 3–6 visualizations for the same text. Pick the one that reads clearest to a stranger, not the flashiest one.\n- Export the diagram as PNG or SVG so you can embed it in your README and slides.\n\n---\n",

  "Gamma": "<!-- primer:platform:gamma -->\n### Concept primer: What is Gamma and how is it different from PowerPoint or Google Slides?\n\n**Gamma** is an AI presentation tool. You type what you want to present (\"a 10-slide pitch for a school recycling club, casual tone\"), and Gamma drafts the entire deck — layout, images, text, and design — in about a minute. From there you edit like a normal slide app, but the starting point is already visually polished.\n\n**Why that's a big deal.** Most students spend 80% of their presentation time on layout and 20% on content. Gamma flips that. The design is handled from the first draft, so you focus on the *ideas and the story* — which is the part that actually earns the grade or wins the pitch.\n\n**Concepts unique to Gamma.**\n\n- **Cards, not slides.** Each \"slide\" is a card that can scroll vertically as well as advance sideways. Great for the web, still exportable to PDF/PowerPoint for classroom projectors.\n- **Themes** — one click restyles the whole deck. Pick one and stick with it.\n- **AI edit** — highlight any block and tell Gamma what to change (\"make this shorter,\" \"add a stat,\" \"turn this into a bulleted list\").\n\n**What still matters (Gamma doesn't do for you).**\n\n- **The story.** A great deck has a clear beginning (the problem), middle (your solution), and end (the ask). Gamma can lay it out; you have to decide what it says.\n- **Truth.** If Gamma auto-generates a statistic, verify it. Same rule as any AI.\n- **Your voice.** Read the draft out loud. Rewrite anything that doesn't sound like you.\n\n---\n",

  "Adobe Firefly": "<!-- primer:platform:firefly -->\n### Concept primer: What is Adobe Firefly and why use it instead of other image generators?\n\n**Adobe Firefly** is Adobe's family of AI image and graphic tools. You type a description (a **prompt**) and Firefly generates images from it. It also powers features inside Photoshop and Illustrator like *Generative Fill* (\"add a mountain here,\" \"remove this person\") and *Text Effects* (turn typography into a themed illustration).\n\n**What makes Firefly different from other image AIs.**\n\n- **Commercially safe by design.** Firefly is trained primarily on Adobe Stock and public-domain content, so the images it generates can be used for school, portfolios, posters, and even commercial projects without the copyright worry that surrounds some other tools.\n- **Style controls.** You can pick a visual style (photo, digital art, watercolor, low-poly), aspect ratio, camera angle, and color palette from menus instead of stuffing everything into the prompt.\n- **Reference images.** Upload an image and Firefly can generate new ones that match its style or composition.\n\n**Prompting an image generator well.** Describe *four things*, in this order, and results improve dramatically:\n\n1. **Subject** — what is in the image? (\"A red fox\")\n2. **Setting / action** — where and doing what? (\"…standing in a snowy forest at sunrise\")\n3. **Style** — what does the art look like? (\"…digital painting, cinematic lighting\")\n4. **Details** — camera, mood, colors, aspect ratio. (\"…wide shot, warm colors, 16:9\")\n\n**Ethics you must respect in this course.**\n\n- Never prompt for real living people or copyrighted characters as if they were yours.\n- Always disclose that the image is AI-generated in your README.\n- Don't use AI images to fake evidence, news, or someone's likeness.\n\n---\n",

  "Replit": "<!-- primer:platform:replit -->\n### Concept primer: What is Replit and why is it a good place to start coding?\n\n**Replit** is a code editor that runs entirely in your browser. There is nothing to install — you open a project (called a **Repl**) and you have a full development environment: a file tree on the left, an editor in the middle, a console and preview on the right. It supports 50+ programming languages, works on a Chromebook, and every project you make gets a public URL you can share.\n\n**Why Replit is ideal for a first coding project.**\n\n- **Zero setup.** Traditional coding tutorials lose beginners at \"install Python, set the PATH, open the terminal.\" Replit skips all of that.\n- **Instant preview.** Click Run and your website or app appears in the built-in browser panel. Every change is a click away from a live result.\n- **Replit AI (Ghostwriter / Agent).** Replit has a built-in AI that can write code, explain code, and fix bugs *inside your project*. You can ask it \"why is this line wrong?\" and it points at the line.\n- **Shareable URLs.** Every Repl has a live URL like `https://your-repl.username.repl.co`. Perfect for portfolios — reviewers click and see your project running immediately.\n\n**A few beginner terms you'll see.**\n\n- **Repl** — one project (files + language + environment).\n- **Run** — the big button that executes your project.\n- **Console** — the black text panel where the program's output and errors appear.\n- **Files pane** — the folder on the left; `index.html` and `main.py` are typical starting files.\n- **Deploy** — publishing your Repl to its permanent public URL.\n\n**Two habits that will save you hours.**\n\n1. Read error messages carefully. The console tells you the file, the line number, and usually a fix. Beginners skip this and guess.\n2. Ask the AI to *explain* code before it writes more. If you can't explain your own project in your own words, you don't own it yet.\n\n---\n"
}
$json$::jsonb;

  rec record;
  new_instructions text;
  new_github_instructions text;
  primer text;
BEGIN
  FOR rec IN
    SELECT a.id, a.platform, a.instructions_md, a.github_instructions_md
    FROM public.assignments a
  LOOP
    new_instructions := rec.instructions_md;
    primer := platform_primers ->> rec.platform;
    IF primer IS NOT NULL AND (new_instructions IS NULL OR position('<!-- primer:platform:' in new_instructions) = 0) THEN
      new_instructions := primer || E'\n' || COALESCE(new_instructions, '');
    END IF;

    new_github_instructions := rec.github_instructions_md;
    IF new_github_instructions IS NULL OR position('<!-- primer:readme -->' in new_github_instructions) = 0 THEN
      new_github_instructions := readme_primer || E'\n' || COALESCE(new_github_instructions, '');
    END IF;

    UPDATE public.assignments
    SET instructions_md = new_instructions,
        github_instructions_md = new_github_instructions
    WHERE id = rec.id;
  END LOOP;
END
$mig$;